#Validation script for megacity-metro
#This is used to validate your catalog-info.yaml 

name: Validate Catalog-info.yaml
on:
  pull_request:
    paths:
      - 'catalog-info.yaml'
  push:
    paths:
      - 'catalog-info.yaml'
    branches: [dev]

jobs:
  validate_catalog:
    runs-on: ubuntu-latest
    steps:
      - id: 'Checkout'
        uses: actions/checkout@v3

      - id: 'Validate'
        uses: 'RoadieHQ/backstage-entity-validator@v0.3.2'